CREATE DATABASE CHAPTER;
USE CHAPTER;
CREATE TABLE CLIENT_MASTER (
    CLIENTNO    VARCHAR(6),
    NAME        VARCHAR(20),
    ADDRESS1    VARCHAR(30),
    ADDRESS2    VARCHAR(30),
    CITY        VARCHAR(20),
    STATE       VARCHAR(20),
    PINCODE     DECIMAL(6),
    REMARKS     VARCHAR(60),
    YTDSALES    DECIMAL(10,2)
);
SELECT *FROM CLIENT_MASTER;
