USE CHAPTER;
CREATE TABLE PRODUCT_MASTER (
    PRODUCTNO       VARCHAR(6),
    DESCRIPTION     VARCHAR(30),
    PROFITPERCENT   DECIMAL(5,2),
    UNITMEASURE     VARCHAR(10),
    QTYONHAND       DECIMAL(10,0),
    REORDERLVL      DECIMAL(10,0),
    SELLPRICE       DECIMAL(10,2),
    COSTPRICE       DECIMAL(10,2),
    AVGRATING       DECIMAL(3,2)
);
SELECT *FROM PRODUCT_MASTER;
